#!/usr/bin/python
import xlrd
import sys, argparse
from args import parse_base
from api.login import login
from api.servicos import servicos
from api.cards import card
from api.operadora import operadora
from excel.servicos import servico
from excel.colaborador import colaborador
from excel.card import cards
from excel.comissao import comissao


parser = argparse.ArgumentParser(
    description = "One system parameterizer"
)
sub = parser.add_subparsers(dest="cmd")
sub.required = True

serv = sub.add_parser("serv",
               help= "manipulating services")
serv.add_argument("-R", "--reset", action="store_true",
                  help= "Delete or inactivate all services")
serv = parse_base(serv)

cols = sub.add_parser("cols",
                      help= "manipulating collaborators")
cols = parse_base(cols)

card_parse = sub.add_parser("card",
                      help= "manipulating cards")
card_parse.add_argument("-R", "--reset", action="store_true",
                  help= "Delete or inactivate all cards")
card_parse= parse_base(card_parse)

com_parse = sub.add_parser("comm",
                      help= "Professional committee manipulation")
com_parse = parse_base(com_parse)

args = parser.parse_args()

try:
    book = xlrd.open_workbook(args.worksheet)
except FileNotFoundError:
    print("File not found!!")
    sys.exit()
except xlrd.biffh.XLRDError:
    print("Unsupported file!!")
    sys.exit()

one = login()
access_token = one.login(
    nome_empresa= args.empresa,
    nome_filial= args.filial,
    email= args.login,
    senha= args.password
)

if args.cmd == "serv":
    if args.reset:
        serv = servicos()
        serv.delete_all()
    servico(book)

if args.cmd == "cols":
    colaborador(book)

if args.cmd == "card":
    if args.reset:
        cd = card()
        cd.delete_all()
        cd.operadora.delete_all()
    cards(book)

if args.cmd == "comm":
    comissao(book)
